type User = {
    /**
     * Id of user generated by database
     */
    id: number,
    /**
     * Users email as entered when created
     */
    email: string,
    /**
     * Users first name as entered when created
     */
    first_name: string,
    /**
     * Users last name as entered when created
     */
    last_name: string,
    /**
     * TBD
     */
    image_filename: string,
    /**
     * TBD
     */
    password: string,
    /**
     * TBD
     */
    auth_token: string
}