type User = {
    /**
     * Id of user generated by database
     */
    id: number,
    /**
     * Users email as entered when created
     */
    email: String,
    /**
     * Users first name as entered when created
     */
    first_name: String,
    /**
     * Users last name as entered when created
     */
    last_name: String,
    /**
     * TBD
     */
    image_filename: String,
    /**
     * TBD
     */
    password: String,
    /**
     * TBD
     */
    auth_token: String
}